### ISSUE TITLE
ionic emulate iOS returns a blank screen

### ISSUE THREAD

**Issue by tjaffri** [leob/ionic-quickstarter#23]
I tried to figure out why, but I can't seem to get any debug output from the iOS emulator.

I did:

> ionic platform add iOS
> gulp build
> ionic emulate iOS

This launches the iOS emulator, but just shows a white screen.

**Comment by leob** [comment]
Did you test it on an actual iOS device apart from an iOS emulator? And did you try an Android emulator?

Actually the only thing I tested (apart from "ionic serve") was with the Ionic View app ("ionic upload") on an Android and an iOS device (iPhone), and with "ionic build/run" on an Android device.

Didn't try iOS or Android emulators, an iOS emulator might be a bit of a problem but I'll have a look one of these days

**Comment by leob** [comment]
I think I found the reason: I included the wrong version of a library js file, leading to a "$moduleErr" error. 

I've just commited a fix (git commit: 4981d5c), please retest.

(note: the whole process for including the libs in both the gulp file and the index-template file and in the app.js file, 3 times, is way too error-prone - we should really fix/simplify this process ...)

**Comment by tjaffri** [comment]
Awesome. Fixed.

**Comment by leob** [comment]
I'll document on the Wiki (here: https://github.com/leob/ionic-quickstarter/wiki/Quickstart-manual#troubleshooting-moduleerr-errors-in-a-production-build) how you can debug this kind of problem (moduleErr errors).

In a nutshell:

1) In index-template.html change "ionicbundle" from 'ionic.bundle.min.js' to 'ionic.bundle.js'  

2) Modify src/lib/ionic/js/ionic.bundle.js as explained here:

```
http://www.chrisgmyr.com/2014/08/debugging-uncaught-error-injectormodulerr-in-angularjs/
```

3) In ionic.project, change "documentRoot" from "src" to "www"

4) Execute:

```
ionic serve -c --browser google-chrome --nogulp
```

   You should now see exactly why you are getting the blank screen (assuming it's a "moduleErr")

5) Revert steps 1 and 3

```
(you can leave the ionic.bundle.js file from step 2 as-is so you can use it next time)
```
