### ISSUE TITLE
Migration to Ionic 1.3.2

### ISSUE THREAD

**Issue by xujingbao** [leob/ionic-quickstarter#40]

**Comment by leob** [comment]
Upgrade to Ionic 1.3.2 is underway ... will commit it tomorrow.

**Comment by leob** [comment]
Done! Just committed a new version with Ionic 1.3.2 support, see the Release Notes (https://github.com/leob/ionic-quickstarter/wiki/Release-notes) for details.

**Comment by xujingbao** [comment]
I did a test, perfect！

**Comment by leob** [comment]
Good to hear that!

I have a few more plans and ideas for improvements. I'm also thinking about publishing the starter on Ionic Market (as a free app of course, nothing changes, it's only a marketing tool).

Ionic 2 is around the corner but the starter still seems to be popular. I'm thinking about creating a similar starter for Ionic 2, although with Ionic 2 a lot of things are already improved out of the box of course.

**Comment by xujingbao** [comment]
I have been looking for such a best practice starer long time,It is very good.

While we are using ionic1.x development of a project, a short period of time will not use ionic2, But really looking foward to the starter for Ionic2 and Angular 2！

**Comment by leob** [comment]
That's great to hear, yes the starter has also been very useful for myself, I'm using it for all my projects. It is my plan to make a starter for Ionic 2 too.
