### ISSUE TITLE
Module 'oauth.utils' is not available!

### ISSUE THREAD

**Issue by xujingbao** [leob/ionic-quickstarter#41]
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.oauthUtil due to:
Error: [$injector:modulerr] Failed to instantiate module oauth.utils due to:
Error: [$injector:nomod] Module 'oauth.utils' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=oauth.utils

**Comment by leob** [comment]
Okay, so when do you get this error? Do you get it when you do a production build/run (on a device, Android or iOS), so with "gulp build ; ionic run android" (or "ionic run ios") ?

The 'missing' module (oauth.utils) should be present in ng-cordova.js (which gets loaded in index.html), so it should be there.

Not clear to me why it's not there. Did you maybe try to upgrade to a newer Ionic version and could it be that the "oauth.utils" module isn't there anymore?

Yes that must be it ... I see that in the newest ng-cordova.js (https://github.com/driftyco/ng-cordova/blob/master/dist/ng-cordova.js) the "oauth" stuff isn't there, it has been removed.

I can also see that there is now a separate library "ng-cordova-oauth" which contains the "oauth.helpers" module.

Okay I'll add that separate lib to the project (concurrently with upgrading to Ionic 1.3.2) and then the issue should be gone.

**Comment by leob** [comment]
Done! Just committed a new version with Ionic 1.3.2 support and a newer ngCordova version which should fix this issue.

See the Release Notes (https://github.com/leob/ionic-quickstarter/wiki/Release-notes) for details.

**Comment by xujingbao** [comment]
good job🤗

leob notifications@github.com于2016年11月8日 周二11:49写道：
